# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\清风幽鸣\Desktop\ROS2学习\pyqt5\auto_drive.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(462, 306)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_backLidar = QtWidgets.QGridLayout()
        self.gridLayout_backLidar.setHorizontalSpacing(6)
        self.gridLayout_backLidar.setObjectName("gridLayout_backLidar")
        self.widget_for_backLidar = QtWidgets.QWidget(self.centralwidget)
        self.widget_for_backLidar.setBaseSize(QtCore.QSize(50, 50))
        self.widget_for_backLidar.setObjectName("widget_for_backLidar")
        self.gridLayout_backLidar.addWidget(self.widget_for_backLidar, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_backLidar, 0, 0, 1, 1)
        self.gridLayout_frontLidar = QtWidgets.QGridLayout()
        self.gridLayout_frontLidar.setHorizontalSpacing(20)
        self.gridLayout_frontLidar.setObjectName("gridLayout_frontLidar")
        self.widget_for_frontLidar = QtWidgets.QWidget(self.centralwidget)
        self.widget_for_frontLidar.setEnabled(True)
        self.widget_for_frontLidar.setObjectName("widget_for_frontLidar")
        self.gridLayout_frontLidar.addWidget(self.widget_for_frontLidar, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_frontLidar, 0, 1, 1, 1)
        self.gridLayout_stateDisplay = QtWidgets.QGridLayout()
        self.gridLayout_stateDisplay.setObjectName("gridLayout_stateDisplay")
        self.left_oil = QtWidgets.QLabel(self.centralwidget)
        self.left_oil.setObjectName("left_oil")
        self.gridLayout_stateDisplay.addWidget(self.left_oil, 0, 0, 1, 1)
        self.main_program_state = QtWidgets.QLabel(self.centralwidget)
        self.main_program_state.setObjectName("main_program_state")
        self.gridLayout_stateDisplay.addWidget(self.main_program_state, 2, 1, 1, 1)
        self.left_oil_state = QtWidgets.QLabel(self.centralwidget)
        self.left_oil_state.setObjectName("left_oil_state")
        self.gridLayout_stateDisplay.addWidget(self.left_oil_state, 0, 1, 1, 1)
        self.right_oil = QtWidgets.QLabel(self.centralwidget)
        self.right_oil.setObjectName("right_oil")
        self.gridLayout_stateDisplay.addWidget(self.right_oil, 1, 0, 1, 1)
        self.main_program = QtWidgets.QLabel(self.centralwidget)
        self.main_program.setObjectName("main_program")
        self.gridLayout_stateDisplay.addWidget(self.main_program, 2, 0, 1, 1)
        self.right_oil_state = QtWidgets.QLabel(self.centralwidget)
        self.right_oil_state.setObjectName("right_oil_state")
        self.gridLayout_stateDisplay.addWidget(self.right_oil_state, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_stateDisplay.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_stateDisplay.setColumnStretch(0, 1)
        self.gridLayout_stateDisplay.setColumnStretch(1, 1)
        self.gridLayout_stateDisplay.setColumnStretch(2, 3)
        self.gridLayout_stateDisplay.setRowStretch(0, 1)
        self.gridLayout_stateDisplay.setRowStretch(1, 1)
        self.gridLayout_stateDisplay.setRowStretch(2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_stateDisplay, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setRowStretch(0, 3)
        self.gridLayout_5.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 这里不再设置尺寸，而是使用全屏模式
        MainWindow.showFullScreen()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_oil.setText(_translate("MainWindow", "左车桥状态："))
        self.main_program_state.setText(_translate("MainWindow", "停止模式"))
        self.left_oil_state.setText(_translate("MainWindow", "未知"))
        self.right_oil.setText(_translate("MainWindow", "右车桥状态："))
        self.main_program.setText(_translate("MainWindow", "主程序状态："))
        self.right_oil_state.setText(_translate("MainWindow", "未知"))
