#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'lidar-data-handler','console_scripts','lidar_data_handler'
__requires__ = 'lidar-data-handler'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('lidar-data-handler', 'console_scripts', 'lidar_data_handler')()
    )
